### ISSUE TITLE
Compile Error :: 'eeprom_size' was not declared in this scope

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/TeensyTransfer#5]
When I try to compile I am getting this error:

** To get compiled code in TeensyTransfer.h I need to edit line 31 :: 
//#define _HAVE_EEPROM

** using IDE 1.6.8 and TDuino:1.28b1

C:\tCode\libraries\TeensyTransfer\TeensyTransfer.cpp: In member function 'void TeensyTransfer::eeprom_read()':

C:\tCode\libraries\TeensyTransfer\TeensyTransfer.cpp:303:19: error: 'eeprom_size' was not declared in this scope

  sz = eeprom_size();

                   ^

Multiple libraries were found for "SerialFlash.h"
 Used: C:\tCode\libraries\SerialFlash
 Not used: I:\Teensy168\hardware\teensy\avr\libraries\SerialFlash
Using library TeensyTransfer in folder: C:\tCode\libraries\TeensyTransfer (legacy)
Using library SerialFlash at version 0.4 in folder: C:\tCode\libraries\SerialFlash 
Using library SPI at version 1.0 in folder: I:\Teensy168\hardware\teensy\avr\libraries\SPI 
Error compiling for board Teensy 3.2 / 3.1.

**Comment by FrankBoesing** [comment]
https://github.com/FrankBoesing/TeensyTransfer/commit/9f16e4f8226f6d85c23edad746ee0c6145ad9cb9

..still wondering what happened..

but thank you :)

**Comment by Defragster** [comment]
let me know what might be out of date or missing the eeprom_size();

**Comment by FrankBoesing** [comment]
solved (email)
