### ISSUE TITLE
Teensy displays version 0

### ISSUE THREAD

**Issue by n8many** [FrankBoesing/TeensyTransfer#9]
When I attempt to use the teensytransfer program from the command line, I get the following error.

`teensytransfer.exe -i teensy`

`teensytransfer: version conflict.`
`PC (this): 1610091856`
`Teensy : 0`

This error happens both when I use the library as well as use the pre-built teensy images. I have also tried changing the version variable to a number in the library and got the same results.

I am using Arduino 1.6.11 with Teensyduino 1.30 on Windows 10 64-bit and trying transfer files to a Teensy LC with a Prop Shield LC attached.

Any ideas what could cause this?

**Comment by FrankBoesing** [comment]
I'll look this evening. Thanks for reporting this issue!

**Comment by FrankBoesing** [comment]
Hi, 
i've fixed some issues - should work now. Can you test it with SPI-Flash ?
I have no hardware for Teensy-LC & SPI-Flash.

**Comment by n8many** [comment]
Tested all of the functions (list, read, write, delete, and erase) and they all work. Thanks, for the help!
